### ISSUE TITLE
URL Hash

### ISSUE THREAD

**Issue by dehenne** [CTeipen/SteemitEva#2]
Da du deutsch verstehst, schreibe ich den Issue mal auf deutsch ^^

Feature Request:
- URL für eine Auswertung

Erklärung:
Damit man nicht immer alles neu eingeben muss am nächsten Tag, wäre es cool wenn man eine eindeutige ID zu seiner Auswertung bekommt

Das könntest du theoretisch folgendermaßen machen:
http://steemiteva.cteipen.de/challenge/@pcsg-dev/win-5-sbd-new-month-new-luck-english-german

Also
http://steemiteva.cteipen.de/[link] :-)

**Comment by CTeipen** [comment]
Habe es jetzt so gelöst:

http://steemiteva.cteipen.de/index.html?author=cuby&link=steemiteva-plus-upvotes

**Comment by dehenne** [comment]
Solangsam wird es nutzbar :+1:
