### ISSUE TITLE
Der Autor des Beitrags oder Kommentars kann nicht immer ausgefüllt werden

### ISSUE THREAD

**Issue by dehenne** [CTeipen/SteemitEva#3]
Der Autor des Beitrags oder Kommentars kann nicht immer ausgefüllt werden.
Copy and Paste funktioniert aber einzelne Eingabe geht nicht.

Manche Buchstaben gehen am Anfang nicht.
Zum Beispiel r, s, t, p

**Comment by CTeipen** [comment]
Ja, weil die als Shortcuts für Funktionen der Tabelle gesetzt sind. Die Shortcuts muss ich dann wohl umlegen oder rausnehmen. Ich schreib es mal auf die Agenda.

**Comment by CTeipen** [comment]
Done :)
