### ISSUE TITLE
Export Follower 

### ISSUE THREAD

**Issue by dehenne** [CTeipen/SteemitEva#6]
Beim Export nach Excel wird zwar eine Follower Spalte angelegt aber diese nicht ausgefüllt.
Vielleicht machst du hier 0 oder 1 rein ;-)

Bei den anderen Export Typen habe ich nicht geschaut. Ist aber bestimmt genauso.

**Comment by CTeipen** [comment]
Das hatte ich schon befürchtet. Sonst gibt es ja und nein 😉
